# swagger.yml

openapi: 3.0.0
info:
  title: "Whatever REST API"
  description: "An API to answer whatever questions you ask"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Question:
      type: "object"
      required:
        - question
      properties:
        question:
          type: "string"
    Chat_settings:
      type: "object"
      properties:
        model:
          type: "string"
        temperature:
          type: "number"
        max_tokens:
          type: "integer"
    Chat_settings2:
      type: "object"
      properties:
        model:
          type: "string"
        temperature:
          type: "number"
        max_tokens:
          type: "integer"
        session_id:
          type: "string"
    Reply:
      type: "object"
      required:
        - reply
      properties:
        reply:
          type: "string"
paths:
  /answer:
    post:
      operationId: "answer.answer"
      tags:
        - Answer
      summary: "Answer a question"
      requestBody:
          description: "Question"
          required: True
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Question"
          x-body-name: "question"
      responses:
        "200":
          description: "Successfully answer user question"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reply"
  /chat:
    post:
      operationId: "answer.chat"
      tags:
        - Chat
      summary: "Chat with LLM"
      requestBody:
          description: "Question"
          required: True
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Question"
          x-body-name: "question"
      responses:
        "200":
          description: "Successfully answer user question"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reply"
  /newchat:
    get:
      operationId: "answer.new_chat"
      tags:
        - Chat
      summary: "Start new chat"
      responses:
        "200":
          description: "Successfully create new chat"
    post:
      operationId: "answer.new_chat_ext"
      tags:
        - Chat
      summary: "Start new chat with selecting model, temp and max_tokens"
      requestBody:
          description: "Chat settings"
          required: True
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chat_settings"
          x-body-name: "chat_settings"
      responses:
        "200":
          description: "Successfully set"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chat_settings2"
  /search:
    post:
      operationId: "answer.search"
      tags:
        - Search
      summary: "Search web to get answer"
      requestBody:
          description: "Question"
          required: True
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Question"
          x-body-name: "question"
      responses:
        "200":
          description: "Successfully answer user question"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reply"